version: "3"

services:
  leavemanager-server:
    container_name: "leavemanager-server"
    restart: always
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      - "mysql"
  
  mysql:
    container_name: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./docker.env
    image: mysql:8
    environment:
      MYSQL_DATABASE: '$$MYSQL_DATABASE'
      MYSQL_USER: '$$MYSQL_USER'
      MYSQL_PASSWORD: '$$MYSQL_PASSWORD'
      MYSQL_ROOT_PASSWORD: '$$MYSQL_ROOT_PASSWORD'
