version: "3"

services:
  leavemanager-server:
    container_name: "leavemanager-server"
    restart: always
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      - "mysql"
  
  mysql:
    container_name: "mysql"
    restart: always
    env_file:
      - ./docker.env
    image: mysql:8
    environment:
      MYSQL_DATABASE: '$$MYSQL_DATABASE'
      MYSQL_ROOT_PASSWORD: '$$MYSQL_ROOT_PASSWORD'
