version: "3"

services:
  leavemanager-server:
    container_name: "leavemanager-server"
    restart: always
    image: 732313143489.dkr.ecr.ap-south-1.amazonaws.com/leavemanager-server:latest
    ports:
      - "4000:4000"
    volumes:
      - /home/ec2-user/storage/public:/app/public
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-south-1
        awslogs-group: leavemanager
        awslogs-stream: application-server-logs

    depends_on:
      - "mysql"
  
  mysql:
    container_name: "mysql"
    restart: always
    env_file:
      - ./docker.env
    image: mysql:8
    environment:
      MYSQL_DATABASE: '$$MYSQL_DATABASE'
      MYSQL_ROOT_PASSWORD: '$$MYSQL_ROOT_PASSWORD'